FROM gradle:8.5-jdk21 AS builder
WORKDIR /app
COPY . .
RUN gradle clean build -x test

FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=builder /app/build/classes/java/main /app/
ENTRYPOINT ["java", "ru.nsu.odnostorontseva.client.KeyGenClient"]
