FROM ubuntu:latest
LABEL authors="Evgenia"
FROM gradle:8.5-jdk21 AS builder

WORKDIR /app
COPY . .

# Собираем fat-jar
RUN ./gen-ca-key.sh
RUN gradle clean shadowJar -x test

FROM eclipse-temurin:21-jdk
WORKDIR /app

COPY --from=builder /app/build/libs/server.jar /app/server.jar
COPY --from=builder /app/src/main/resources/ca-pkcs8.key /app/ca-pkcs8.key

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/server.jar"]
